### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by r0f1** [RafayGhafoor/Subscene-Subtitle-Grabber#5]
Hi, none of the Hello World examples seem to be working. Starting subgrab (without any commands) runs forever until I force a close with [Ctrl]+[C]. Starting subgrab to search something immediately returns with an empty line. 
I am using Python 3 and Windows. I tested subgrab with the default command line and cygwin and both in normal mode and with administrative rights.

**Comment by RafayGhafoor** [comment]
```Starting subgrab (without any commands) runs forever until I force a close with [Ctrl]+[C].```

Initiating subgrab without any commands, makes it filter the media files in the working directory and then operate the download process on the filtered directory. The reason for it not halting might be because you're operating it in a directory which contains a huge amount of folder. 
For example, your typical root directory (C:\) which contains (windows) systems files, user data etc. 

To speed up the process, the approach that I recommend is to create a [Media Files] folder and then issue subgrab in the folder directory.

```Starting subgrab to search something immediately returns with an empty line.```

Subgrab uses Subscene default provider for searching subtitles and its release page was down for the past 3-4 days. It appears to be working fine now.

![image](https://user-images.githubusercontent.com/20343475/48365928-20a2ed00-e6ce-11e8-8406-d556e4cff64b.png)

![image](https://user-images.githubusercontent.com/20343475/48365912-12ed6780-e6ce-11e8-9197-4aaaadb197ae.png)
